package simple;

import com.ftn.sbnz.model.models.users.Patient;
import com.ftn.sbnz.model.models.users.OperatedPatient;
import com.ftn.sbnz.model.models.examinations.Examination;
import com.ftn.sbnz.model.models.examinations.ExaminationState;
import com.ftn.sbnz.model.models.examinations.Symptom;
import com.ftn.sbnz.model.models.examinations.SymptomFrequency;
import com.ftn.sbnz.model.models.examinations.ExaminationType;
import com.ftn.sbnz.model.models.examinations.TumorType;
import com.ftn.sbnz.model.models.examinations.TestResult;
import com.ftn.sbnz.model.models.examinations.Diagnosis;
import com.ftn.sbnz.model.models.examinations.TNMKlassification;
import com.ftn.sbnz.model.models.therapy.Therapy;
import com.ftn.sbnz.model.models.therapy.Operation;
import com.ftn.sbnz.model.models.therapy.PaliativeCare;
import com.ftn.sbnz.model.models.therapy.TherapyState;
import com.ftn.sbnz.model.models.therapy.TherapyType;

import java.time.LocalDateTime;
import java.util.Set;

global Set<String> criticalSymptoms;

rule "Critical Blood Pressure Alert"
when
    $patient : Patient(bloodPressure > 180 || bloodPressure < 90)
then
    System.out.println("Alert: Critical change in blood pressure detected. Value: " + $patient.getBloodPressure());
end

rule "Critical Pulse Alert"
when
    $patient : Patient(puls > 120 || puls < 50)
then
    System.out.println("Alert: Critical change in pulse detected. Value: " + $patient.getPuls());
end

rule "Critical Oxygen Saturation Alert"
when
    $patient : Patient(saturationO2 < 90)
then
    System.out.println("Alert: Critical change in oxygen saturation detected. Value: " + $patient.getSaturationO2());
end

rule "Critical Body Temperature Alert"
when
    $patient : Patient(bodyTemperature > 39 || bodyTemperature < 36)
then
    System.out.println("Alert: Critical change in body temperature detected. Value: " + $patient.getBodyTemperature());
end

