export enum TumorType {
    INTRATHORACAL_PULMONARY = 'INTRATHORACAL_PULMONARY',
    INTRATHORACAL_NONPULMONARY = 'INTRATHORACAL_NONPULMONARY',
    EXTRATORACAL_PULMONARY = 'EXTRATORACAL_PULMONARY',
    EXTRATORACAL_NONPULMONARY = 'EXTRATORACAL_NONPULMONARY'
}
